/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import modeloConection.ConexaoBD;
import ModeloDao.DaoMedico;
import javax.swing.JComboBox;
import modeloBeans.BeanslMedicos;

/**
 *
 * @author William
 */
public class FormMedico extends javax.swing.JFrame {
    
    BeanslMedicos mod = new BeanslMedicos();
    DaoMedico control = new DaoMedico();
    ConexaoBD conex = new ConexaoBD();
    int flag = 0;
   
    public FormMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField1Crm = new javax.swing.JFormattedTextField();
        jTextField1Nome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jComboBoxEspecialista = new javax.swing.JList();
        jButton1Novo = new javax.swing.JButton();
        jButton2Salvar = new javax.swing.JButton();
        jButton3Cancelar = new javax.swing.JButton();
        jButton4Editar = new javax.swing.JButton();
        jButton5Excluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMedicos = new javax.swing.JTable();
        jTextField1Pesquisa = new javax.swing.JTextField();
        jButton6Pesquisar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtCOD = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Nome:");

        jLabel3.setText("CRM:");

        jLabel4.setText("Especialista:");

        jFormattedTextField1Crm.setEnabled(false);

        jTextField1Nome.setEnabled(false);

        jScrollPane1.setEnabled(false);

        jComboBoxEspecialista.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Cirurgião", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jComboBoxEspecialista);

        jButton1Novo.setText("Novo");
        jButton1Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1NovoActionPerformed(evt);
            }
        });

        jButton2Salvar.setText("Salvar");
        jButton2Salvar.setEnabled(false);
        jButton2Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2SalvarActionPerformed(evt);
            }
        });

        jButton3Cancelar.setText("Cancelar");
        jButton3Cancelar.setEnabled(false);
        jButton3Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3CancelarActionPerformed(evt);
            }
        });

        jButton4Editar.setText("Editar");
        jButton4Editar.setEnabled(false);
        jButton4Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4EditarActionPerformed(evt);
            }
        });

        jButton5Excluir.setText("Excluir");
        jButton5Excluir.setEnabled(false);

        jTableMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableMedicos);

        jButton6Pesquisar.setText("Pesquisar");
        jButton6Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6PesquisarActionPerformed(evt);
            }
        });

        jLabel5.setText("ID:");

        jtCOD.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1Novo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2Salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextField1Crm, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6Pesquisar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtCOD, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(263, 263, 263))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5Excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4Editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtCOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1Novo)
                            .addComponent(jTextField1Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2Salvar)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextField1Crm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3Cancelar)
                    .addComponent(jTextField1Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6Pesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4Editar)
                        .addGap(11, 11, 11)
                        .addComponent(jButton5Excluir))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(303, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cadastros de Médicos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(556, 446));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2SalvarActionPerformed
        if(flag==1){
        mod.setNome(jTextField1Nome.getText());
        mod.setEspecialidade((String) jComboBoxEspecialista.getSelectedValue());
        mod.setCrm(Integer.parseInt(jFormattedTextField1Crm.getText()));
        control.Salvar(mod);
        jTextField1Nome.setText("");
        jFormattedTextField1Crm.setText("");
        jTextField1Nome.setEnabled(false);
        jFormattedTextField1Crm.setEnabled(false);
        jComboBoxEspecialista.setEnabled(false);
        jButton2Salvar.setEnabled(false);
        }else{
         mod.setCodigo(Integer.parseInt(jtCOD.getText()));
         mod.setNome(jTextField1Nome.getText());
         mod.setEspecialidade((String)jComboBoxEspecialista.getSelectedValue());
         mod.setCrm(Integer.parseInt(jFormattedTextField1Crm.getText()));
         control.Editar(mod);
         jtCOD.setText("");
         jTextField1Nome.setText("");
         jFormattedTextField1Crm.setText("");
        jTextField1Nome.setEnabled(false);
        jFormattedTextField1Crm.setEnabled(false);
        jComboBoxEspecialista.setEnabled(false);
        jButton2Salvar.setEnabled(false);
        jButton1Novo.setEnabled(true);
        jButton3Cancelar.setEnabled(false);
        
        }
    }//GEN-LAST:event_jButton2SalvarActionPerformed

    private void jButton1NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1NovoActionPerformed
        flag = 1;
        jTextField1Nome.setEnabled(true);
        jFormattedTextField1Crm.setEnabled(true);
        jComboBoxEspecialista.setEnabled(true);
        jButton2Salvar.setEnabled(true);
        jButton3Cancelar.setEnabled(true);
    }//GEN-LAST:event_jButton1NovoActionPerformed

    private void jButton6PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6PesquisarActionPerformed
        mod.setPesquisa(jTextField1Pesquisa.getText());
        BeanslMedicos model = control.buscaMedicos(mod);
        jTextField1Nome.setText(model.getNome());
        jtCOD.setText(String.valueOf(model.getCodigo()));
        jFormattedTextField1Crm.setText(String.valueOf(model.getCrm()));
        jComboBoxEspecialista.setSelectedValue(model.getEspecialidade(), rootPaneCheckingEnabled);
        jButton4Editar.setEnabled(true);
        jButton5Excluir.setEnabled(true);
    }//GEN-LAST:event_jButton6PesquisarActionPerformed

    private void jButton3CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3CancelarActionPerformed
        jTextField1Nome.setEnabled(!true);
        jFormattedTextField1Crm.setEnabled(!true);
        jComboBoxEspecialista.setEnabled(!true);
        jButton2Salvar.setEnabled(!true);
        jButton3Cancelar.setEnabled(!true);
        jButton1Novo.setEnabled(true);
        jButton4Editar.setEnabled(false);
        jButton5Excluir.setEnabled(false);
    }//GEN-LAST:event_jButton3CancelarActionPerformed

    private void jButton4EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4EditarActionPerformed
        flag = 2;
        jTextField1Nome.setEnabled(true);
        jFormattedTextField1Crm.setEnabled(true);
        jComboBoxEspecialista.setEnabled(true);
        jButton2Salvar.setEnabled(true);
        jButton3Cancelar.setEnabled(true);
        jButton4Editar.setEnabled(false);
        jButton1Novo.setEnabled(false);
        jButton5Excluir.setEnabled(false);
    }//GEN-LAST:event_jButton4EditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Novo;
    private javax.swing.JButton jButton2Salvar;
    private javax.swing.JButton jButton3Cancelar;
    private javax.swing.JButton jButton4Editar;
    private javax.swing.JButton jButton5Excluir;
    private javax.swing.JButton jButton6Pesquisar;
    private javax.swing.JList jComboBoxEspecialista;
    private javax.swing.JFormattedTextField jFormattedTextField1Crm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableMedicos;
    private javax.swing.JTextField jTextField1Nome;
    private javax.swing.JTextField jTextField1Pesquisa;
    private javax.swing.JTextField jtCOD;
    // End of variables declaration//GEN-END:variables
}
