/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import static java.lang.reflect.Array.set;
import javax.swing.JOptionPane;

/**
 *
 * @author William
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1Senha = new javax.swing.JPasswordField();
        jButton1Acessar = new javax.swing.JButton();
        jTextField1Usuario = new javax.swing.JTextField();
        jLabel1Senha = new javax.swing.JLabel();
        jLabel1Usuario = new javax.swing.JLabel();
        jButton1Sair = new javax.swing.JButton();
        jLabel1FundoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jPasswordField1Senha);
        jPasswordField1Senha.setBounds(230, 120, 160, 40);

        jButton1Acessar.setText("Acessar");
        jButton1Acessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1AcessarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Acessar);
        jButton1Acessar.setBounds(230, 180, 71, 23);

        jTextField1Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1UsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1Usuario);
        jTextField1Usuario.setBounds(230, 90, 160, 30);

        jLabel1Senha.setText("Senha");
        getContentPane().add(jLabel1Senha);
        jLabel1Senha.setBounds(180, 130, 40, 14);

        jLabel1Usuario.setText("Usuario");
        getContentPane().add(jLabel1Usuario);
        jLabel1Usuario.setBounds(180, 100, 50, 14);

        jButton1Sair.setText("Sair");
        jButton1Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SairActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Sair);
        jButton1Sair.setBounds(320, 180, 51, 23);

        jLabel1FundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundotelaLogin.png"))); // NOI18N
        jLabel1FundoLogin.setText("jLabel1");
        getContentPane().add(jLabel1FundoLogin);
        jLabel1FundoLogin.setBounds(-5, 0, 610, 320);

        setSize(new java.awt.Dimension(509, 359));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1UsuarioActionPerformed

    private void jButton1AcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1AcessarActionPerformed
      if(jTextField1Usuario.getText().equals("admin")&&jPasswordField1Senha.getText().equals("1234")){
        TelaPrincipal tela = new TelaPrincipal();
      tela.setVisible(true);
      dispose();
      }else{
          JOptionPane.showConfirmDialog(rootPane, "Senha ou Usuário inválidos!");
      }
      
    }//GEN-LAST:event_jButton1AcessarActionPerformed

    private void jButton1SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1SairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Acessar;
    private javax.swing.JButton jButton1Sair;
    private javax.swing.JLabel jLabel1FundoLogin;
    private javax.swing.JLabel jLabel1Senha;
    private javax.swing.JLabel jLabel1Usuario;
    private javax.swing.JPasswordField jPasswordField1Senha;
    private javax.swing.JTextField jTextField1Usuario;
    // End of variables declaration//GEN-END:variables
}
