/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import modeloConection.ConexaoBD;

/**
 *
 * @author William
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    ConexaoBD conecta = new ConexaoBD (); 
    
    public TelaPrincipal() {
        initComponents();
        conecta.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame2BemVindo = new javax.swing.JInternalFrame();
        jPanel1Internal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1CadMedico = new javax.swing.JButton();
        jButton1CadEnfermeiras = new javax.swing.JButton();
        jButton1CadPacientes = new javax.swing.JButton();
        jButton1Agenda = new javax.swing.JButton();
        jLabel1PainelFundo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1FecharBemVindo = new javax.swing.JButton();
        jLabel1FundoPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1Cadastros = new javax.swing.JMenu();
        jMenuItem1CadMedico = new javax.swing.JMenuItem();
        jMenuItem1CadPacientes = new javax.swing.JMenuItem();
        jMenuItem2CadEnfermeira = new javax.swing.JMenuItem();
        jMenuItem3CadUsuários = new javax.swing.JMenuItem();
        jMenu2Relátorios = new javax.swing.JMenu();
        jMenu1Ferramentas = new javax.swing.JMenu();
        jMenuItem1TelaBemVindo = new javax.swing.JMenuItem();
        jMenu3Sair = new javax.swing.JMenu();
        jMenuItem1Sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrame2BemVindo.setTitle("Bem Vindo");
        jInternalFrame2BemVindo.setVisible(true);
        jInternalFrame2BemVindo.getContentPane().setLayout(null);

        jPanel1Internal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1Internal.setLayout(null);

        jLabel2.setText("Cadastros =");
        jPanel1Internal.add(jLabel2);
        jLabel2.setBounds(10, 0, 80, 14);

        jLabel3.setText("Agenda -");
        jPanel1Internal.add(jLabel3);
        jLabel3.setBounds(10, 130, 50, 14);

        jButton1CadMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CadMedicos.png"))); // NOI18N
        jButton1CadMedico.setToolTipText("Médicos");
        jButton1CadMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CadMedicoActionPerformed(evt);
            }
        });
        jPanel1Internal.add(jButton1CadMedico);
        jButton1CadMedico.setBounds(0, 20, 120, 100);

        jButton1CadEnfermeiras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-infermeira.png"))); // NOI18N
        jButton1CadEnfermeiras.setToolTipText("Enfermeiras");
        jPanel1Internal.add(jButton1CadEnfermeiras);
        jButton1CadEnfermeiras.setBounds(123, 20, 80, 100);

        jButton1CadPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadPacientes.png"))); // NOI18N
        jButton1CadPacientes.setToolTipText("Pacientes");
        jPanel1Internal.add(jButton1CadPacientes);
        jButton1CadPacientes.setBounds(203, 20, 80, 100);

        jButton1Agenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Agenda.png"))); // NOI18N
        jButton1Agenda.setToolTipText("Agendamento");
        jPanel1Internal.add(jButton1Agenda);
        jButton1Agenda.setBounds(10, 150, 100, 60);

        jLabel1PainelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/internalframe.png"))); // NOI18N
        jPanel1Internal.add(jLabel1PainelFundo);
        jLabel1PainelFundo.setBounds(0, -10, 530, 250);

        jInternalFrame2BemVindo.getContentPane().add(jPanel1Internal);
        jPanel1Internal.setBounds(0, 50, 530, 210);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Sistema de Gerenciamento de:");
        jInternalFrame2BemVindo.getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 260, 22);

        jButton1FecharBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jButton1FecharBemVindo.setToolTipText("Fechar Tela Bem-Vindo");
        jInternalFrame2BemVindo.getContentPane().add(jButton1FecharBemVindo);
        jButton1FecharBemVindo.setBounds(470, 0, 73, 50);

        getContentPane().add(jInternalFrame2BemVindo);
        jInternalFrame2BemVindo.setBounds(0, 30, 560, 350);

        jLabel1FundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_telaprincipal.jpg"))); // NOI18N
        getContentPane().add(jLabel1FundoPrincipal);
        jLabel1FundoPrincipal.setBounds(0, 0, 550, 360);

        jMenu1Cadastros.setText("Cadastros");

        jMenuItem1CadMedico.setText("Médicos");
        jMenuItem1CadMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1CadMedicoActionPerformed(evt);
            }
        });
        jMenu1Cadastros.add(jMenuItem1CadMedico);

        jMenuItem1CadPacientes.setText("Pacientes");
        jMenu1Cadastros.add(jMenuItem1CadPacientes);

        jMenuItem2CadEnfermeira.setText("Enfermeiras");
        jMenu1Cadastros.add(jMenuItem2CadEnfermeira);

        jMenuItem3CadUsuários.setText("Usuários");
        jMenu1Cadastros.add(jMenuItem3CadUsuários);

        jMenuBar1.add(jMenu1Cadastros);

        jMenu2Relátorios.setText("Relátorios");
        jMenuBar1.add(jMenu2Relátorios);

        jMenu1Ferramentas.setText("Ferramentas");

        jMenuItem1TelaBemVindo.setText("Tela Bem Vindo");
        jMenuItem1TelaBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1TelaBemVindoActionPerformed(evt);
            }
        });
        jMenu1Ferramentas.add(jMenuItem1TelaBemVindo);

        jMenuBar1.add(jMenu1Ferramentas);

        jMenu3Sair.setText("Sair");

        jMenuItem1Sair.setText("Sair");
        jMenuItem1Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1SairActionPerformed(evt);
            }
        });
        jMenu3Sair.add(jMenuItem1Sair);

        jMenuBar1.add(jMenu3Sair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(577, 474));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1SairActionPerformed
        conecta.desconecta();
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1SairActionPerformed

    private void jMenuItem1TelaBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1TelaBemVindoActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1TelaBemVindoActionPerformed

    private void jMenuItem1CadMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1CadMedicoActionPerformed
      FormMedico tela = new FormMedico();
      tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem1CadMedicoActionPerformed

    private void jButton1CadMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CadMedicoActionPerformed
         FormMedico tela = new FormMedico();
      tela.setVisible(true);
    }//GEN-LAST:event_jButton1CadMedicoActionPerformed

    private void jButtonFecharBemVindoActionPerformed(java.awt.event.ActionEvent evt){
        jInternalFrame2BemVindo.dispose();
    }
            
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Agenda;
    private javax.swing.JButton jButton1CadEnfermeiras;
    private javax.swing.JButton jButton1CadMedico;
    private javax.swing.JButton jButton1CadPacientes;
    private javax.swing.JButton jButton1FecharBemVindo;
    private javax.swing.JInternalFrame jInternalFrame2BemVindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1FundoPrincipal;
    private javax.swing.JLabel jLabel1PainelFundo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1Cadastros;
    private javax.swing.JMenu jMenu1Ferramentas;
    private javax.swing.JMenu jMenu2Relátorios;
    private javax.swing.JMenu jMenu3Sair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1CadMedico;
    private javax.swing.JMenuItem jMenuItem1CadPacientes;
    private javax.swing.JMenuItem jMenuItem1Sair;
    private javax.swing.JMenuItem jMenuItem1TelaBemVindo;
    private javax.swing.JMenuItem jMenuItem2CadEnfermeira;
    private javax.swing.JMenuItem jMenuItem3CadUsuários;
    private javax.swing.JPanel jPanel1Internal;
    // End of variables declaration//GEN-END:variables
}
